[package]
name = "reutils"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug-level = 2
opt-level = "z"
lto = true
codegen-units = 1

[profile.release]
panic = "abort"
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
libc = { version = "0.2" }
phf = { version = "0.11.1", features = ["macros"] }
getargs = "0.5.0"
