[package]
name = "reutils"
version = "0.1.0"
edition = "2021"
authors = ["Elizabeth Myers", "Malina Thomas"]

[profile.dev]
debug = true
opt-level = 2
lto = true

[profile.release]
panic = "abort"
strip = true
opt-level = "z"
lto = true
codegen-units = 1

[dependencies]
getargs = "0.5.0"
libc = { version = "0.2" }
phf = { version = "0.11.1", features = ["macros"] }
notify = { version = "6.0.0", default-features = false, features = ["macos_kqueue"] }
